 # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PreRelease

on:
  push:
    branches:
      - prerelease
    tags:
      - 'v*alpha*'
      - 'v*beta*'
      - 'v*rc*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    #     - run: npm test
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Zip output
      run: |
        zip -r ancl-loader${{ steps.package-version.outputs.current-version }}.zip dist-main/*
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.package-version.outputs.current-version }}
        name: ${{ steps.package-version.outputs.current-version }}
        prerelease: true
        draft: true
        files: ancl-loader${{ steps.package-version.outputs.current-version }}.zip