 # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release alpha

on:
  pull_request:
    branches: [ alpha ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    #     - run: npm test
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Zip output
      run: |
        zip -r ancl-loader.alpha-${{ steps.package-version.outputs.current-version }}.zip dist-main/*
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
    # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ steps.package-version.outputs.current-version }}
        automatic_release_tag: ${{ steps.package-version.outputs.current-version }}-alpha
        prerelease: true
        files: |
          ./**/*.zip